### ISSUE TITLE
Calling render does not re-render table with new data

### ISSUE THREAD

**Issue by sjurgis** [ghiscoding/slickgrid-universal#129]
### Your Environment
Slickgrid inside Salesforce LWC

### Describe the Bug
Calling render does not re-render table with new data

### Steps to Reproduce
- Render table
- Add row to underlying data collection
- call .render()

### Expected Behavior
New table row should appear 

### Current Behavior
Nothing happens, no error either

### Possible Solution
Perhaps calling some method like addRow, but tbh table should be reactive to begin with.
The API documentation is missing.

### Code Sample
```    @track data = [
        {id: 1, name: "Oli Bob", age: "12", col: "red", dob: ""}]
        var columns = [
            {id: "name", name: "Name", field: "name", type: Slicker.Enums.FieldType.string, editor: { model: Slicker.Editors.text }},
            {id: "age", name: "Age", field: "age"},
            {id: "col", name: "Favourite Color", field: "col"},
            {id: "dob", name: "Date Of Birth", field: "dob"},
        ]
renderedCallback(){
        var options = {
            editable: true,
            enableCellNavigation: true,
            enableColumnReorder: false
        };
        this.grid = new Slicker.GridBundle(div, columns, options, this.data);
}
addData(){
        this.data = [...this.data, {
            id: this.data.length + 1,
            name: "Margret Marmajuke" + this.data.length + 1,
            age: 20 + this.data.length + 1 + '',
            col: "yellow" + this.data.length + 1,
            dob: "31/01/1999"
        }]
        this.grid.slickGrid.render()
}
```

**Comment by ghiscoding** [comment]
That won't work because you're expecting the dataset variable to have a Setter but it not connected that way. There is a Setter which does the re-render of the grid but it's outside the constructor, you need to call it this way

```ts
this.grid.dataset = [ /*...*/ ];
```

Perhaps I can change that in the future but for most of the constructor arguments are 1 time variables and the Setters are all from the GridBundle.

Also just a side note, it would be better to change the variable name `this.grid` to something else because you could confuse it with `slickGrid` and I'm saying this because very often in my docs I will use `grid` when it's the SlickGrid object which is not the same as the `Slicker.GridBundle`, I use `sgb` across my docs instead.

**Comment by ghiscoding** [comment]
Closing as no feedback was provided and the answer provided in previous comment should resolve the issue
