### ISSUE TITLE
gridstate sortcolumns field instead id property of column

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/slickgrid-universal#1467]
### Describe the bug

hey there,

when using the OData Service in combo with gridstate events to persist the user selection to e.g localstorage I do get errors when restoring cols on next refresh.

the root cause was brought down to the columnId containing the field property instead of the id as seen here

https://github.com/ghiscoding/slickgrid-universal/blob/38b465cb8ebcdd6012b939677a4367c2dce010e9/packages/odata/src/services/grid-odata.service.ts#L548

I didnt dig deeper but guess there were reasons for doing so in order to make sorting work. do you know why or should I dig deeper?

### Reproduction

* activate odata service
* add gridstate change listener
* store to localstorage 
* apply to preset when refreshing

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | latest |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zewa666** [comment]
looking at the graphql implementation, where its done correctly https://github.com/ghiscoding/slickgrid-universal/blob/38b465cb8ebcdd6012b939677a4367c2dce010e9/packages/graphql/src/services/graphql.service.ts#L587  , this perhaps was simply a mistake

**Comment by ghiscoding** [comment]
oh ok yeah that must be a typo error, I'd be ok to change it since yes it's supposed to be the column `id` as the name suggest (which is often but not always identical to the column `name`). By the way, I had to click on the link you provided and open it to see the difference, I'm not sure if you knew or not but you should select multiple lines then click on copy permalink to be able to see a few lines in here (note that this only works with code that is in the same repo, for example that wouldn't work pasting Angular-Slickgrid permalink code in here)

![image](https://github.com/ghiscoding/slickgrid-universal/assets/643976/dfe039cb-e01d-47bb-accd-38bdaa9aeaa4)

and that gives me this, the other good thing is that it's also assigned to a commit, so if the code changes in the future, the link will always point to the old code :)

https://github.com/ghiscoding/slickgrid-universal/blob/38b465cb8ebcdd6012b939677a4367c2dce010e9/packages/graphql/src/services/graphql.service.ts#L587-L590

**Comment by zewa666** [comment]
ok I'll create a PR for that. good opportunity to read up on the OData implementation

**Comment by jr01** [comment]
We currently only store the columns (not sorters and not filters) from the grid state in our backend, so we won't be affected by the fix :)
