### ISSUE TITLE
Filter for blanks / non blanks

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/slickgrid-universal#1569]
### Clear and concise description of the problem

Similar to Excel it would be helpful if we could filter e.g. text columns to only show blank / non blank cells

https://docs.aspose.com/cells/net/how-to-filter-blanks-and-non-blanks/2.png

### Suggested solution

I'm not sure where to place that feature. One idea I had was about an advanced filter, signaled by a gear icon placed next to the filter, which would popup a menu. in there buttons for blank/non blank could be placed. so it would be somewhat similar to the command popup.

### Alternative

so far I can simulate non blanks by setting does not equal and `""` as filter value. but that feels a bit weird

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
if it's a Compound Filter then it's nearly the same as this recent SO [Question](https://stackoverflow.com/questions/78592213/in-the-list-filter-the-starts-with-operator-a-filters-the-value-with-a-with) which brought a bug that I fixed yesterday in PR #1566 with the option `skipCompoundOperatorFilterWithNullInput` (see associated [docs](https://ghiscoding.gitbook.io/slickgrid-universal/column-functionalities/filters/compound-filters#how-to-avoid-filtering-when-only-operator-dropdown-is-changed))

If you just want to filter blank/non-blank in the cell with a regular filter then just use `<>`, taking [Example 11](https://ghiscoding.github.io/slickgrid-universal/#/example11), I see that it works for returning blank (by using `<> `, however there seems to be a bug with `!=` which is supposed to be equivalent to `<>` but currently behaves differently). 

~For the non-blank value then I don't think we have any ways currently to return them unless you use a Compound Filter without enabling `skipCompoundOperatorFilterWithNullInput`~ Actually there's a way which I just remembered, you can simply use `> a` (or `> 0`) and that will work because the values are compared against the ASCII table (case sensitive). 

However, it's a bit weird that typing `<> ` returns non-blank, I was expecting the inverse and that's probably a bug with the regex. As for the non-blank then I think `> a` is a totally fine way of getting these values

**Comment by zewa666** [comment]
thanks for the hints and also `skipCompoundOperatorFilterWithNullInput`, good to know about that. yet the problem is that UX wise these feels a bit weird for a non-tech user.

another perhaps simpler approach would be to add a custom operator that ignores the value and mereley builds the blank/non-blank condition by itself.

**Comment by ghiscoding** [comment]
well I mean we could have extra Compound Operators that could return blanks/non-blanks without typing anything (just selecting the operator) but that might feel a little weird because all the other operators expect the user to type a value. 

For a regular text input then I don't really know, what did you have in mind exactly? Personally I feel ok with just using `<> ` and `> a` because once the user knows it, it's easy to remember (though less techy users might not understand the ASCII table stuff) and actually by looking at the table again it's safer to use `> A` because `A` index is lower than `a`

On the other hand, the ASCII code above will probably just work with local JSON dataset, and probably not (or behave differently) with any Backend Services.

I think it's one of those thing that is good to have a cheat sheet not too far (perhaps some kind of Legend accessible maybe via the Grid Menu), I mean for the shortcuts that you can do directly with built-in filters. I presented some of them to our users couple years ago and they were a little impressed by these tricks.

**Comment by ghiscoding** [comment]
I found the cheat sheet I had created years ago for the built-in filters, so here it is. By looking at it, I now realized what's the difference between `<>` and `!=`, they are not equivalent after all, I had completely forgot the differences 😆 

![image](https://github.com/ghiscoding/slickgrid-universal/assets/643976/048f0fe5-6bc5-4acd-ad00-53fd653c2459)

**Comment by zewa666** [comment]
yeah as said I feel a bit lost myself in where to add those. I'll bounce back to our users and see what they think of your proposed approach. the chest sheet is huge and adding it to the command window as a help page is a fantastic idea 🎉

I'll let ya know what came out and worst case I can give a couple of ideas a shot and share some progress here if you're fine keeping this open. on the other hand if you feel that is way out of standard grid features please feel free to close the issue

**Comment by ghiscoding** [comment]
We can keep it open until  you circle back to your users and if anything comes out of it then we'll create a PR, otherwise close the issue later.

But anyway I have to look into why typing `<> ` is returning non-blanks when it should be the inverse, so that seems like a bug that I need to investigate (probably the regex)

**Comment by zewa666** [comment]
oh yeah I just meant thanks for the tip, we'll create our own help page ofc.

exclusively OData. So in that case I still have a chance to manipulate the filter also on the backend to turn it into something that matches SQL.

**Comment by ghiscoding** [comment]
> exclusively OData. So in that case I still have a chance to manipulate the filter also on the backend to turn it into something that matches SQL.

ok but I still wish to align the operator, so whatever you decide to use, I'd like to have a common approach for both local and backend since it's always more desirable to always filter the same way for both (less confusing for the user who don't care if you use backend or local dataset)

**Comment by ghiscoding** [comment]
> I now realized what's the difference between `<>` and `!=`, they are not equivalent after all, I had completely forgot the differences

Considering this difference, I think we might need some adjustments in the Backend Service(s) though it looks like OData doesn't have any "not contains" query filter. Do we need adjustment or should we keep them as is?

https://github.com/ghiscoding/slickgrid-universal/blob/91ef50b205e5da4fdeff32a439b565557644ae87/packages/odata/src/services/grid-odata.service.ts#L215-L218

**Comment by zewa666** [comment]
thats a good catch.

for odata checking for blanks needs also to respect nulls. So `xyz ne null AND xyz ne ""` would be what I need I guess but thats perhaps already non-standard logic

**Comment by ghiscoding** [comment]
@zewa666  I'll let you deal with that one then, if you think it needs any fixes or not. It looks like it's possible to make a distinction in GraphQL for "not contains" vs "not equal" but it might not be easy to do with OData (or not without extra or duplicate query like you suggested) so that might not be possible for all backend services. Do what you think is best since you are a user and I'm not 😉 

Perhaps again circling back to @jr01 since he might also bring his point of view on this filter search for blank/non-blanks with OData and "not contains" vs "not equal"

**Comment by jr01** [comment]
Yes, to filter for non blanks you should use: `$filter=Name ne '' and Name ne null`.

In oData you can use `$filter=not contains(Name, '')`, but in my quick testing it returned no rows at all. I guess `contains(Name, '')` (without the not) is logically always true because every string (even the blank ones) will contain the empty string by definition.

**Comment by jr01** [comment]
https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_BuiltinFilterOperations

**Comment by zewa666** [comment]
@jr01 thanks for the confirmation. but do you also agree that this is a somewhat OData specific imolementation hence might not suitable for slickgrid filter standards?

my intention right now, after @ghiscoding's insights, goes towards the direction to create a custom filter with said advanced menu and buttons for blank/non blank so we don't clutter the standard slickgrid experience.

**Comment by jr01** [comment]
Well, from a user perspective it is very nice to have "(Blank)" as an option I think.  For example, in a dropdown like the Company filter:
![image](https://github.com/ghiscoding/slickgrid-universal/assets/2624681/57d967a1-e8c6-4531-a4fc-987b1b81fbee)

I imagine it could have values "Select all, ABC, XYZ, (Blank)" and the latter would select those customers that don't have a company.

**Comment by ghiscoding** [comment]
just a side note and not to get confused with similar terms here, the single select filter also accepts an empty (aka blank) value which is meant to "return everything". You could maybe add a "(blanks)" value instead to return blanks. So @zewa666 what was your vision here? I mean did you wanted to expand on an input text filter or did you want to use a select filter with extra values like "(blanks)" and "(non-blanks)"? If you want to use the select filter then I guess there's nothing to do here since you can already do this today by just adding these extra values. 

![image](https://github.com/ghiscoding/slickgrid-universal/assets/643976/b11664c1-45c4-4ba4-b7e9-6b68701deca7)

**Comment by zewa666** [comment]
I'll go ahead with a custom filter as example to show what I meant. post it here once I've got a POC

**Comment by zewa666** [comment]
alright, here it is.

Witness my hacky wacky CSS skills of the popup 🤣 
![additional_filters_popup](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/704f506a-7a7b-4e6c-984a-b52d55e4999f)

**Comment by ghiscoding** [comment]
hmm to me this seems more like a "Create your own Custom Filter" situation, I'm saying this mostly because as per your demo it's already doable by just typing the correct characters to make it work. The only other thing I could think is to create another type of filter that would have these 2 options and maybe flip the dropdown position from the left to the right so that it's more obvious as being different than Compound Filter but... again I'm not sure if I really want to add this into the project though, this seems overkill to me and mostly just a matter of training your users (adding a Docs into the Grid Menu might suffice) 

Also a side note, I created the Compound Filters by using Bootstrap [input group](https://getbootstrap.com/docs/5.3/forms/floating-labels/#input-groups)

**Comment by zewa666** [comment]
well my idea with this was along the lines of filter templates for users. so instead of them having to remember things, we fill them in for them. Hence why the list should be configurable from a collection of commands perhaps placed directly on the filter property of the column. and thats why it should potentially also work for all sorts of filters. the user can still go ahead and write/click their own filter.

But as you properly noted, this is already a very narrow use case plus one easily achievable in user land code, I'll just use the generic `params` on the filter property to store my commands. I'm equally not sure if it should be a standard feature but just wanted to share the idea and check back what you think.

that said, please feel free to close the issue.

**Comment by ghiscoding** [comment]
if we look at how Ag-Grid does it, it has some good and bad part in their implementation. They have a small pyramid icon on the right side of each column filter. The bad side is that if you choose most type of >, <=, ... then it won't appear when you close the modal except for the little blue dot (so my Compound Filter approach is better than theirs I think) but on the other hand they show a readonly filter as "blank" or "nonBlanks" when we choose either of these 2, which seems like a good approach (at least now they show these 2 filter types)

![msedge_1TNxCRn6NH](https://github.com/ghiscoding/slickgrid-universal/assets/643976/e7329171-233e-4110-b0e5-25d66b29c5cb)

The Ag-Grid approach makes me think of 2 ways we can do it, 1st would be like them with an extra icon or the 2nd approach, it just makes me think of the Header Button (for that though we would need to get the instance ref of each filter in order to do anything with them OR use the dynamic filter method), and there's actually a 3rd approach maybe via a context menu over the filter (this one would much simpler to implement but less visible to the user)

also curious of what @jr01 thinks on all of that too

**Comment by ghiscoding** [comment]
Here it is, 2 shortcuts in Header Menu via a sub-menu. It works "as is" and you can simply code the code below and try it for yourself 🚀 

Couple of things to note though, I say it works "as is" but the code could be improved a little. With the code below, I'm calling `setValues()` but that doesn't trigger the keyup event, so I need to call the `callback()` method myself. However, technically speaking each filter already their own `protected onTriggerEvent()` (or something similar, since it may vary depending on each type of filter), but a much simpler code, I could add a 3rd argument to the `setValues(searchTerms, operator, triggerCallback)` so that it would trigger by itself and I wouldn't have to know the callback arguments of each filter. Also note that the position in the header menu can be adjusted by a `positionOrder` that I added a while ago to sort them however I want them in the command list.

With all of that in mind, I think what we could potentially do is to maybe provide an extra property in the Column interface that could loop through a list of Filter Shortcuts and add it to the Header Menu by itself instead of requiring the user to add them like the code below. I think this approach is ok and does not clutter the UI while also being visible to the end user. 

Note I used `< 0` just because of its char index in the ASCII table (or use `< A` if you're sure that it starts with a character, I'm not sure why they decided to put `A` before `a` though) and technically speaking if we also want to use special chars as text then maybe `< #` is better... long story short, see ASCII table for proper filtering

```ts
this.columnDefinitions = [
{
  id: 'countryOfOrigin', name: 'Country of Origin', field: 'countryOfOrigin',
  header: {
    menu: {
      commandItems: [
        {
          command: 'filter-shortcuts',
          iconCssClass: 'mdi mdi-filter-outline',
          title: 'Filter Shortcuts',
          commandItems: [
            {
              command: 'filter-blanks',
              title: 'Filter Blanks',
              iconCssClass: 'mdi mdi-filter-minus-outline',
              action: () => {
                const filterRef = this.sgb.filterService.getFiltersMetadata().find(f => f.columnDef.id === 'countryOfOrigin');
                if (filterRef) {
                  const searchTerms = ['< 0'];
                  filterRef.setValues(searchTerms);
                  filterRef.callback(undefined, { columnDef: filterRef.columnDef, operator: filterRef.operator, searchTerms, shouldTriggerQuery: true });
                }
              }
            },
            {
              command: 'filter-non-blanks',
              title: 'Filter Non-Blanks',
              iconCssClass: 'mdi mdi-filter-plus-outline',
              action: () => {
                const filterRef = this.sgb.filterService.getFiltersMetadata().find(f => f.columnDef.id === 'countryOfOrigin');
                if (filterRef) {
                  const searchTerms = ['> 0'];
                  filterRef.setValues(searchTerms);
                  filterRef.callback(undefined, { columnDef: filterRef.columnDef, operator: filterRef.operator, searchTerms, shouldTriggerQuery: true });
                }
              }
            },
          ]
        },
      ]
    }
  },
}];
```

![brave_OBbiwRrDEL](https://github.com/ghiscoding/slickgrid-universal/assets/643976/085456d1-5d94-4df3-8ff9-bc6d8a05a2e5)

**Comment by zewa666** [comment]
holy moly and I thought so often this looks familiar 😄

**Comment by zewa666** [comment]
hmm now there is a new tricky one ... a number filter ... any ideas how to search for blanks/non blanks here? :)

**Comment by ghiscoding** [comment]
I'm not sure why but `< Infinity` actually removes the blanks, I was expecting the inverse but anyway it works and you add negative for the inverse so `> -Infinity`, the only problem is you can't type that in a number input so you will have to use the regular text input for that to work

**Comment by ghiscoding** [comment]
<img src="https://pbs.twimg.com/media/CV5UzgHW4AAx6xC.jpg" alt="alt text" width="250" height="250">

**Comment by zewa666** [comment]
I didnt have the chance to talk to our users but think that could be a good + standard way to do it. I personally wouldnt do that globally. In general I'm not a fan of these kind of fallbacks as I prefer explicit column configuration as it becomes a challenge to trace all potential hops when you're searching for why something happens as it does.

so if not explicitly required I'd go with columns first and add the global on popular demand

**Comment by ghiscoding** [comment]
Yeah I mean that would be like most other flags like for example `exportWithFormatter`, if you define it in your grid options and have not defined in your column then the grid option will be used.. however if you have it defined in your column and the grid option then the column has a higher index so the column flag will be used and that's the typical approach that I do for most of these options, it's easy to do and it brings you the flexibility to do it the way you want.

**Comment by zewa666** [comment]
i get that, just not a fan of it ;)

but our users are big fans of the header menu idea. So if you need a review for your PR please count me in

**Comment by zewa666** [comment]
> > I now realized what's the difference between `<>` and `!=`, they are not equivalent after all, I had completely forgot the differences
> 
> Considering this difference, I think we might need some adjustments in the Backend Service(s) though it looks like OData doesn't have any "not contains" query filter (well I found this [alternative](https://stackoverflow.com/a/72843747/1212166)). Do we need adjustment or should we keep them as is?
> 
> OData
> 
> https://github.com/ghiscoding/slickgrid-universal/blob/91ef50b205e5da4fdeff32a439b565557644ae87/packages/odata/src/services/grid-odata.service.ts#L215-L218
> 
> GraphQL
> 
> https://github.com/ghiscoding/slickgrid-universal/blob/91ef50b205e5da4fdeff32a439b565557644ae87/packages/common/src/services/utilities.ts#L428-L432

well actually I've tried it now out with something like `(not contains(OrderNo, 'AX1507170'))` and my sql helper manages to convert that to `WHERE NOT ([OrderNo] like 'AX1507170')`

@jr01 could you tell me what interprets your OData query and is not able to produce a NOT Contains?

@ghiscoding since I've already subclassed GridOdataService for other purposes I can easily override updateFilters and map `<>` manually to using:
```typescript
override updateFilters(
    columnFilters: ColumnFilters | CurrentFilter[],
    isUpdatedByPresetOrDynamically?: boolean
  ): void {
    Object.values(columnFilters).forEach((filter) => {
      if (filter.operator === "<>") {
        filter.operator = OperatorType.notContains;
      }
    });
    super.updateFilters(columnFilters, isUpdatedByPresetOrDynamically);
  }
```

**Comment by ghiscoding** [comment]
> How oData `contains` to SQL `LIKE` should be translated is perhaps debatable and I can imagine there differnet libraries make different choices. To avoid any of that just use the `$filter=Name ne '' and Name ne null` for non blanks.

I think that a special case could be acceptable for the blank use case, you might just need to tweak this if condition

https://github.com/ghiscoding/slickgrid-universal/blob/3e165cf33da53337ac9e157ab919e2056e537c72/packages/odata/src/services/grid-odata.service.ts#L476

**Comment by zewa666** [comment]
@jr01 oh ok I get the confusion I've created now. well the not contains scenario was mainly mentioned to fix the current behavior of `<>` resulting in `ne` which is wrong in all cases. the blank/non blanks we handled with the new filter templates feature.

**Comment by ghiscoding** [comment]
@zewa666 are you going to create a PR for this or were you waiting for more comments from @jr01? I pushed a couple of fixes and wanted to know if I should go ahead with a new patch release or wait for a possible PR from your side? There's no rush though, just asking. 

I think I'm done with pretty much everything and I don't see any other fixes or features to do at this point

**Comment by zewa666** [comment]
nope all good. I'm not sure its a huge benefit and more of an edge case, so I'm fine having this taken care in our own codebase especially since we're gonna modify it further with treatments for empty/null coverage. thx for all the work of yours

**Comment by ghiscoding** [comment]
okie dokie, will push a patch this weekend
