### ISSUE TITLE
about "Row Selection" and "enableExcelCopyBuffer"

### ISSUE THREAD

**Issue by hwlv** [ghiscoding/slickgrid-universal#1616]
### Clear and concise description of the problem

  /**
   * Defaults to true, which leads to use an Excel like copy buffer that gets copied in clipboard and can be pasted back in Excel or any other app.
   * NOTE: please note that this option will NOT work when "Row Selection" & "Row Move" are enabled, because features are conflicting with each other.
   */
  enableExcelCopyBuffer?: boolean;
  
  
  
  I hava problem about this。when you use enableExcelCopyBuffer，you can cancel row select。so "enableExcelCopyBuffer" can use with "Row Selection" together。you can watch this. https://handsontable.com/docs/react-data-grid/demo/

### Suggested solution

I hava problem about this。when you use enableExcelCopyBuffer，you can cancel row select。so "enableExcelCopyBuffer" can use with "Row Selection" together。you can watch this. https://handsontable.com/docs/react-data-grid/demo/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
just because you want it, doesn't mean that the library can do it. The error message is correct, you **cannot** use the Excel Copy Buffer (CellSelectionModel) at the same time as the Row Selection (RowSelectionModel) because they use different Selection Models and SlickGrid can only load 1 Selection Model at a time in SlickGrid and not 2 different model that it would require for this use case. 

If you want to use a hack that works, you can try this Stack Overflow solution
https://stackoverflow.com/a/76810071/1212166

but it's really just a hack and will not be supported by SlickGrid. 

I'm closing this issue since there's no changes to do and it will still not be supported
