### ISSUE TITLE
how to select column data

### ISSUE THREAD

**Issue by hwlv** [ghiscoding/slickgrid-universal#1617]
### Clear and concise description of the problem

I would like to request the addition of a feature to support column selection. This feature should:

1. Allow users to click on a column header to select the entire column.
2. Maintain the column selection state when scrolling or resizing the grid.
3. Provide a visual indication of the selected column (e.g., by applying a specific CSS class).

### Suggested solution

any thing

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
Sorry but I won't be adding this feature, only Row Selection is currently available. SlickGrid never supported Column Selection and I am not intending to work on this either. This would most probably require a new Selection Model for Column Selection and I must again remind you that SlickGrid only accepts 1 Selection Model at a time, so if you ever create a Column Selection, you would not be able to use it at the same time as the Row Selection Model (which is probably not what you want)... So with this known limitation (1 Selection Model at a time) and considering that it would require a whole new Selection Model, I am not going to work on this myself. If you want to contribute a Pull Request for that new feature, that would be nice... otherwise it probably won't be implemented by myself.

**Comment by ghiscoding** [comment]
Column Selection is not supported and I have no intention to support it either, however you could subscribe to header or other click event like `onHeaderClick` or `onClick` (for cell click) and apply some CSS yourself, I assume you will need to use the `!important` prop on the CSS

CSS
```css
.row-selected {
    background-color: pink !important;
}
```

Event Subscribe
```ts
this._bindingEventService.bind(this.gridContainerElm, 'onheaderclick', (e: any) => {
      const args = e.detail.args;

      // remove all previous row selected CSS class
      document.querySelectorAll('.row-selected').forEach(c => c.classList.remove('row-selected'));

      // add new row selected CSS class
      const colIdx = this.sgb.columnDefinitions.findIndex(c => c.id === args.column.id);
      document.querySelector(`[data-id=${args.column.id}]`)?.classList.add('row-selected');
      document.querySelectorAll(`.l${colIdx}`).forEach(c => c.classList.add('row-selected'));
    });
```

Result

![image](https://github.com/user-attachments/assets/2d6a3dc6-18dd-43d8-9d82-8d7df20a3262)

The only downside is that clicking on any header column will sort that column.
