### ISSUE TITLE
Home/End keys in active editor

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/slickgrid-universal#1686]
### Describe the bug

When a cell editor is focused, the arrow keys left and right are intercepted and cell navigation disabled. This is good as it allows to navigate within the Inputs text. Same works with CTRL + Left/Right to jump to start/end of the editor.

what does not work is hitting the pos1 (jumps to first cell of row) or end key (jumps to last cell of the active row)

I wonder whether this is an expected behavior or a bug. I can provide a PR if this indeed is an unintended behavior

### Reproduction

see above

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Hmm I'm not sure what is Pos1, perhaps it's because I'm currently on the laptop. So far, what I can find is that there's some arrow listener in the input editor for arrow left/right, but anything else with Ctrl is about copy/paste for Ctrl+C, Ctrl+V, Ctrl+S or Ctrl+Z apart from that I'm not sure what would catch the event, you can maybe debug that in developer tool.

https://github.com/ghiscoding/slickgrid-universal/blob/3c6ce204dd9b48091b4c49c5c07b5799b3af34b9/packages/common/src/editors/inputEditor.ts#L115-L121

Also another important thing to note is that cell navigation is really only working when `autoCommitEdit` is set to False

**Comment by zewa666** [comment]
ups sry I'm used to german layouts and Pos1 (Position1) is its take on the home key 😅

the ctrl + left/right works because the same listener is stopping direct propagation.

**Comment by ghiscoding** [comment]
most probably an unwanted behavior, so I would think the same as you and consider this a bug
