### ISSUE TITLE
Change target in tsconfig to es5 instead of es2018?

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [ghiscoding/slickgrid-universal#297]
### Your Environment

| Software             | Version(s) |
| -------------------- | ---------- |
| Slickgrid-Universal  | 0.12.0       |
| TypeScript           | 4.2.3        |
| Package Name         | @slickgrid-universal        |

### Context or Topic

slickgrid-universal specifies a target of 2018 in its tsconfig.json.  This breaks IE.  I figured this was intentional, but I noticed aurelia-slickgrid still targets es5.  Since aurelia-slickgrid takes out a dependency on slickgrid-universal, au-slickgrid effectively has a target of 2018 as well.  Would it be possible to change the target in slickgrid-universal to be es5?  We still have users on IE and won't be dropping support until after Microsoft drops support in O365 apps later this year.

### Expected Behavior

See above

### Current Behavior

See above

### Possible Solution

make tsconfig target es5 instead of es2018.

**Comment by ghiscoding** [comment]
wow yes it was intentional, from my understanding IE11 is/was already EOL, I'm not sure that I really want to go that route of putting back the target to ES5, it will make the dist bigger only to support IE11 for just a few months!?! Even Aurelia 2 is targeting ES2018, I followed their settings. Aurelia-Slickgrid is still targeting ES5 simply because I forgot to go and update it. 
The best I could do is to potentially add a script to run an es5 build but I don't wish to update the CommonJS target. Can't that be fixed by simply adding a polyfill?
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.js"
    integrity="sha256-qyG2LBYZavhW0RXdL7CQGGv2dX4WP30uIFPguGoOLjE=" crossorigin="anonymous"></script>
```

@zewa666 @3cp what are your position on the subject? cjs, esm and ES5 target that is...

--- 

and from this MS Article [Microsoft apps and services to end support for Internet Explorer 11](https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-support-end-dates), it's not at the end of this year, it's around mid-August 2021

![image](https://user-images.githubusercontent.com/643976/112652559-e8765200-8e23-11eb-97c7-7683c9bcd635.png)

**Comment by zewa666** [comment]
I personally agree in that its not worth the hassle and if the polyfill approach works its a good workaround for until IE gets finally laid to rest

**Comment by ItWorksOnMyMachine** [comment]
Well, after pulling the code down, updating the tsconfig files, rebuilding for es5, and incorporating the es5 version as an alias in my project's webpack.config, I realize that the dependency on dequal blows away the IE possibility.  Only dequal/lite supports IE, and it has missing features that slickgrid-universal depends on.  Unfortunately, this means I'll have to drop back to to version 2 until we can officially sunset IE.

**Comment by ghiscoding** [comment]
@ItWorksOnMyMachine if it's only `dequal` being the problem (which I added recently because I wanted to replace `lodash.isequal` which was much bigger), I could replace `dequal` with `dequal/lite`, it doesn't support Set & Map but I don't really need it for that anyway, I mainly use it to compare against objects and arrays, the usage are in the Select Filter/Editor, Grid State and Pagination and they're all using objects and/or arrays. If you get it to work with `dequal/lite`, I'd be totally open for a PR, it's even slightly smaller

**Comment by ItWorksOnMyMachine** [comment]
I'm not sure if dequal was the only thing breaking IE, once I hit the dequal dependency I stopped.  There could be more.  Slickgrid Version 2 works, so I figured I'd stick with that until we officially drop IE support later this year then upgrade.  I appreciate your looking at this.  I think your targeting of es2018 is appropriate, we all need to move on from IE and more libraries dropping support for it just means we can get there faster.
