### ISSUE TITLE
The quantity of selected and filtered items is summing the rows of titles and totals of the groupings

### ISSUE THREAD

**Issue by mcallegario** [ghiscoding/slickgrid-universal#469]
### Your Environment

| Software               | Version(s) |
| --------------------- | ---------- |
| Slickgrid-Universal  | x.y        |
| TypeScript               | x.y        |
| Package Name        | x.y        |

### Describe the Bug
When we perform grouping, the number of records displayed in the footer is considering the lines of grouping titles and grouping totals, this bug also occurs in the number of selected items.

### Steps to Reproduce
Just perform groupings and display the metrics of selected and filtered records compared to the real quantity displayed in the grid

### Expected Behavior
The number of items selected and filtered must be the same as those being displayed in the grid

### Current Behavior
The quantity of selected and filtered items is summing the rows of titles and totals of the groupings

![image](https://user-images.githubusercontent.com/44271732/132231890-4ec568e4-4a15-4e6f-8ed9-54f855b321f4.png)

**Comment by ghiscoding** [comment]
good catch that's because it returns row count not the item count, it would probably work by replacing the first argument of the event handler `handleOnItemCountChanged` by [dataView.getFilteredItemCount()](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L299). 

It would be nice if you can test this out and perhaps contribute with a Pull Request?

https://github.com/ghiscoding/slickgrid-universal/blob/5d6454e9f175b8694f372a7e26492ae573eb918f/packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts#L835-L848

**Comment by mcallegario** [comment]
Yes, I think we also have to adjust the selected items method. (getAllSelectedIds / getAllSelectedItems)
Vou tentar contribuir com um Pull Request. 
thanks.
![image](https://user-images.githubusercontent.com/44271732/132253149-f901f453-a69c-4a4f-8740-44f82ebc853b.png)

**Comment by ghiscoding** [comment]
> Yes, I think we also have to adjust the selected items method. (getAllSelectedIds / getAllSelectedItems)

I'm not sure why these methods need to be modified? Can you provide more details? Ahh nevermind, I see now from your print screen but that will have to be fixed on that other repo [6pac/SlickGrid](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js) which is not mine, also there was a new version released just a few days ago so there won't be any new release for some time. I suggest to create a Pull Request on that other repo and use the filter to out `undefined` (I guess that could also be the fix in the PR to create in that other repo). I don't use grouping so often and when I did then it wasn't with row selection so I've never noticed this bug

> Vou tentar contribuir com um Pull Request.

I'm not sure exactly what it means, is it that you will try to contribute? I speak French/English but not more than that :P

**Comment by mcallegario** [comment]
Oops!!
Sorry, I wrote in my language (pt-BR).
Wanted said, "I'll try to contribute a Pull Request."
It is my first experience in this environment.
;-)

**Comment by ghiscoding** [comment]
@mcallegario 
I fixed the original issue for the item count in the footer via PR #473 
As for the DataView `getAllSelectedIds()` I troubleshooted because I wanted to fix the source, rather than just excluding undefined Ids (which is just patching the issue). So after troubleshooting it, I found the issue to be in the Checkbox Selector plugin, we need to exclude grouping rows whenever we click on the "Select All" and if you haven't noticed it was really only happening when clicking that button, if you were clicking only rows in the grid it wasn't showing the issue. 
  - for that I created this [PR](https://github.com/6pac/SlickGrid/pull/635) in the core lib and below is a demo with both PR code change & fixes
  
![xkfat5wyJP](https://user-images.githubusercontent.com/643976/132392438-f8215684-39cc-4f97-9bca-17c53b630fde.gif)

**Comment by mcallegario** [comment]
@ghiscoding 
Yes, today I analyzed the SlickGrid(slick.checkboxselectcolumn.js) code and came to the same conclusion, that the selected items problem only occurs when we use the "select All" checkbox.
I believe that with the adjustment below in the code, will fix the origin of this bug.

![image](https://user-images.githubusercontent.com/44271732/132395890-4fb18e21-da3d-48a9-a294-966051f7c702.png)

**Comment by ghiscoding** [comment]
oh I never used the `__nonDataRow` property before, I already pushed a PR in the core lib with `__group` and `__groupTotals` which is the same as `__nonDataRow` it looks like. Either or they should both fix the issue, it should be merged soon. I'll probably ask the other repo maintainer to push a new version in his repo as well, it'd be nice to have all fixes in my new version as well
