### ISSUE TITLE
Will cell range selection be supported?

### ISSUE THREAD

**Issue by gopal-abbineni** [ghiscoding/slickgrid-universal#594]
Hello, Is this grid will support Cell range selection (Selecting multiple cells by dragging / clicking)? If not do we have any plans to implement ?

**Comment by ghiscoding** [comment]
Your question is not very clear but I believe what you're asking is already doable, you just have to code it. I don't have Examples for everything but you can find plenty more on SlickGrid (core lib) in [Examples list](https://github.com/6pac/SlickGrid/wiki/Examples), also a recent PR #584 made in my lib will bring support to auto-scroll while selecting (by cell or by row), it's merged but not released, you can see the code in the new [Example 17](https://github.com/ghiscoding/slickgrid-universal/blob/master/examples/webpack-demo-vanilla-bundle/src/examples/example17.ts), the second grid does row selection by mouse selection 

Also please open a Discussion instead of an issue when it's... well not an issue, also consider asking any code question on Stack Overflow

**Comment by ghiscoding** [comment]
@gopal-abbineni 
I just released the new version `1.2.0` which includes the new live [Example 17](https://ghiscoding.github.io/slickgrid-universal/#/example17) demo that I mentioned earlier, so you can now see it live. 

You can also check the new [Release 1.2.0](https://github.com/ghiscoding/slickgrid-universal/releases/tag/v1.2.0) to see what's new and you can also upvote ⭐ if you like the lib, cheers 😉
